### PR TITLE
Move Tools to Files (Redo)

### PR DESCRIPTION
**Pull request by johndjameson**
This branch moves existing tools to individual files in the `tools` directory.

### CODE REVIEW

**Comment by drewbarontini** [comment]
🙌  Is this ready to merge? 😬

**Comment by johndjameson** [comment]
Nope, I’ll ping for review when it’s done.

**Comment by johndjameson** [comment]
@drewbarontini What’s your stance on tool classes for color variables themselves? I [added them](https://github.com/spellbook/css/pull/20/files#diff-8e2b688fd2ca906b21ba4e8735747ed5), but I assume we’d want `slate-1` at some point, so they might as well make their way into the map.

**Comment by drewbarontini** [comment]
🤔 We could turn the map into this then...

```scss
$palette: (
  sun: (
    0: $sun
  ),
  slate: (
    0: $slate,
    1: lighter($slate, 50%),
    2: lighter($slate, 70%),
    3: lighter($slate, 90%)
  ),
  white: (
    0: $white
  )
);
```

And then generate `.sb-bc-slate`, `.sb-bc-slate-1`, etc. Thoughts?

**Comment by johndjameson** [comment]
Having the role colors is useful though. They state intention when reading through the code and should be easier to maintain.

Having them both in the same map would make using functions and mixins easier. Maybe we set up two maps and combine them with `map-merge` ([docs](http://sass-lang.com/documentation/Sass/Script/Functions.html#map_merge-instance_method))?

Thinking something like `$colors` and `$role-colors`, then merging them into `$palette`

**Comment by drewbarontini** [comment]
I like that idea. We should probably work on this in isolation to see how we'd want that to work.

**Comment by drewbarontini** [comment]
@johndjameson What is the status of this one? I can pick it up and get it merged in.

**Comment by drewbarontini** [comment]
Going to merge this one in and we can iterate.

**Pull request merged**
