### PR TITLE
Color Management

### LINKED ISSUE #18: Create better color management
I want to set the palette variables, but also have a `$colors` or `$palette` map that we can create a `palette()` function to pull from. I'm thinking this:

```scss
@function palette($key, $value: 0) {
  @return map-get(map-get($palette, $key), $value);
}
```

```scss
$sun: #f4bc40;
$slate: #2f2f2f;
$white: #fff;

$palette: (
  action: (
    0: $sun
  ),
  base: (
    0: $slate,
    t1: tint($slate, 50%),
    t2: tint($slate, 70%),
    t3: tint($slate, 90%)
  ),
  light: (
    0: $white
  )
);
```

```scss
body {
  background-color: palette('base', 't1');
}
```

### PR DESCRIPTION
**Pull request by drewbarontini**
Fixes #18

### CODE REVIEW

**Comment by johndjameson** [comment]
Cool with the setup, but since this moves away from variables can we do `-1` and `1` instead of `s1` and `t1`? Easier to follow IMO.

**Comment by drewbarontini** [comment]
My only concern with that is how easy it is to follow when you call it. That was the only reason I went with the "shade" and "tint" prefixes. Do we think `palette('base', '-2')` is better than `palette(`base', 's2')`? I'm cool with that, but want to make sure.

**Comment by johndjameson** [comment]
Yeah, I think negative for darker intuitively. I always have to translate tint and shade in my head when using `t` and `s` prefixes. Also, then we can kill the quotation marks. Just an idea, but I hope it’ll make things simpler. Maybe not 🙃 

Probably good for others to weigh in.

cc @jordanwade

**Comment by drewbarontini** [comment]
I'm totally down for that. I'll fix the conflicts and add that so we can get this merged in.

**Comment by johndjameson** [comment]
Ah, I just remembered that the resulting tool classes will still use `t1` and `s1`. So… yeah.

**Comment by jordanwade** [comment]
Yeah, I'm with JDJ tint and shade have always confused me on which one is which, using negative for darker makes more sense to me 😁

**Comment by drewbarontini** [comment]
Ugh. I forgot about the tool classes. We could change the name of the `tint` and `shade` functions, and then figure out a better name for the classes.

**Comment by johndjameson** [comment]
We use the `n` prefix for negative values. Maybe use it for “negative“ colors too:

```
.sb-red-n1
.sb-red
.sb-red-1
```

**Comment by drewbarontini** [comment]
The annoyance with that one is that the tool generation needs the key in the map, so it'd have to be `n1: shade($blah, 20%)` in the map, which is weird.

Thinking... 🤔  💭

**Pull request merged**
