### PR TITLE
Create Link Module

### LINKED ISSUE #9: Create Link Module

### PR DESCRIPTION
**Pull request by drewbarontini**
Fixes #9

### CODE REVIEW

**Comment by johndjameson** [comment]
Let’s switch to `sb-link--underlined` and use `text-decoration: underline`. That should be the [default](https://css-tricks.com/styling-underlines-web/#article-header-id-9) unless we want to do something special. ✨

**Comment by drewbarontini** [comment]
@johndjameson So you're saying that `.sb-link--underlined` replaces `.sb-link--bordered`?

**Comment by johndjameson** [comment]
I’d think so. It’s easy enough to add `sb-link--bordered` if we really need it, but let’s use the browser underline to start.

We made that switch on .com and I think it makes sense here too.

**Review by dandenney — APPROVED** [review]
I thought I had found something, but it was already covered https://github.com/spellbook/css/blob/60e6973d2d7c654e0ece4d368f41a4c6fa16ef51/spellbook/_1_reset.scss#L55

You guys are the worst, but also the best!

**Comment by drewbarontini** [comment]
Since we add `text-decoration: none;` to the root `a` tag, it's unnecessary on the `sb-link`, so you did make me catch something, @dandenney!

**Comment by drewbarontini** [comment]
Actually, going to leave `text-decoration: none;` in there in case it's used as a standalone module without the reset where it's explicitly removed. Merging!

**Pull request merged**
